### ISSUE TITLE
运行空白了

### ISSUE THREAD

**Issue by whqgo** [Yiuman/bpmn-vue-activiti#40]
控制台 报错  

Uncaught TypeError: Cannot read properties of undefined (reading 'modules')

**Comment by Yiuman** [comment]
node版本是多少  是否安装了依赖？

**Comment by liuzongyang255** [comment]
同上，node 16.13.2  14.19.3  都试过了  不行，源码里的14.14.22装不上

**Comment by Yiuman** [comment]
走国内镜像试过了吗

**Comment by dannyxu2015** [comment]
同上，node v16.15.0
```
__vue-jsx-ssr-register-helper:7 Uncaught TypeError: Cannot read properties of undefined (reading 'modules')
    at comp.setup (__vue-jsx-ssr-register-helper:7:18)
    at callWithErrorHandling (runtime-core.esm-bundler.js:154:22)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7131:29)
    at setupComponent (runtime-core.esm-bundler.js:7087:11)
    at mountComponent (runtime-core.esm-bundler.js:5096:13)
    at processComponent (runtime-core.esm-bundler.js:5071:17)
    at patch (runtime-core.esm-bundler.js:4673:21)
    at render2 (runtime-core.esm-bundler.js:5791:13)
    at mount (runtime-core.esm-bundler.js:4081:25)
    at app.mount (runtime-dom.esm-bundler.js:1319:23)
```
